From centos:7.7.1908
RUN rpm -ivh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
RUN yum -y install nginx
VOLUME /volume
EXPOSE 80
USER nginx
ADD html.tar.gz /usr/share/nginx/
USER root
ENTRYPOINT ["nginx", "-g", "daemon off;"]