version: '3.7'
services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    image: jenkins_docker_k8s
    container_name: jenkins
    restart: unless-stopped
    volumes:
      - jenkins_volume:/var/jenkins_home
    ports:
      - 80:8080
volumes:
  jenkins_volume:
    driver: local
